### ISSUE TITLE
Fail gracefully if there is not sufficient treatment overlap.

### ISSUE THREAD

**Issue by jtibshirani** [swager/grf#252] opened 2018-06-10 22:49 UTC
For the causal forest algorithm to work, there must be sufficient overlap among similar samples in terms of their treatment. Currently when given data with very little overlap, `causal_forest` may fail with an error along the lines of `Error in t.default(T) : argument is not a matrix`.

We should aim to detect the case where there is not sufficient overlap, and fail with an informative error message. By default before training a causal forest, we calculate treatment propensities (`W.hat` in the code), and this may be a natural point to test for low overlap.

**Comment by halflearned** [comment] 2018-07-13 06:15
Interesting. I got this error message before.

But is this really due to insufficient overlap? [This example](https://gist.github.com/halflearned/30a1e1f5b81cb95b97fb7687252e725b) has zero overlap, but causal forest still runs. (The predictions are incorrect, but the code doesn't fail).

**Comment by jtibshirani** [comment] 2018-07-14 21:38
I agree this needs further fleshing out -- I'll try to dig up the example where we first encountered the issue. Do you remember any details on when you've seen the error message before?

**Comment by halflearned** [comment] 2018-07-15 23:59
Ok, at least one source of errors can be attributed to `DiceKriging`. [Here](https://gist.github.com/halflearned/eb54423187ee3d2d9e15a0230dd4688e)'s how it gives weird errors depending on what it receives for `response` and `noise.var`.

These errors are triggered whenever we try to use tuning. [Here](https://gist.github.com/halflearned/1ed2180ce790d2bb63040b38a31f5369)'s a minimal example of this playing out when we try to tune a `regression_forest` but the outcome changes very little.

In `causal_forest`, we will see this error during the `W.hat` computations: if `W` is mostly constant and `tune.parameters=TRUE` then [this](https://github.com/swager/grf/blob/df90bfb5a4cd269e7e92831b8a1c6fb121dbd7f1/r-package/grf/R/causal_forest.R#L148) step will fail with that error.

**Comment by swager** [comment] 2018-07-16 16:17
That's surprising -- thanks! I guess this is rather concerning if it suggests that DiceKriging may just unexpectedly crash on us...

**Comment by swager** [comment] 2018-08-16 19:38
Closing this as it looks like the core problem is with DiceKriging being unstable, and we're tracking that in #278

**Closed by swager** 2018-08-16 19:38 UTC
Labels: 1.0 release, bug
